version: '3.8'

services:
  # Service PHP + Apache (build from Dockerfile)
  php:
    container_name: mvc_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  mariadb:
    container_name: mvc_mariadb
    image: mariadb:10.7
    restart: always
    ports:
      - "${DB_PORT_EXPOSED}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    container_name: mvc_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
